project:
  type: website
  output-dir: docs

website:
  title: "Vicente Tejero"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: contact.qmd
        text: Contact
        

format:
  html:
    theme: simplex
    css: styles.css
    toc: true
    include-after-body: footer.html

editor: visual